FROM nginx

MAINTAINER Guruprashanth Krishnegowda <guruprashanth.k@iaiyo.in>

COPY default.conf /etc/nginx/conf.d/default.conf
COPY materialize.min.css /data/bde-css/materialize.min.css
COPY bde-hadoop.css /data/bde-css/bde-hadoop.css
